kind: pipeline
name: default

steps:
  # don't have any tests yet so just check it builds
- name: install
  image: python:3.8.0-alpine3.10
  commands:
  - pip install -e .
- name: pypi_publish
  image: plugins/pypi
  when:
    event: [ tag ]
  settings:
    username: 
      from_secret: pypi_username
    password: 
      from_secret: pypi_password